@extends('layouts.app')

@push('styles')
    @vite(['resources/css/content-blocks.css'])
    {{-- Swiper CSS (CDN) --}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
@endpush

@section('content')
    <div class="container content-blocks">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h1 class="h4 mb-0">Создать контент-блок</h1>
            <a href="{{ route('admin.content-blocks.index') }}" class="btn btn-secondary">Отмена</a>
        </div>

        <form action="{{ route('admin.content-blocks.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="mb-3 text-center">
                <label for="title" class="form-label">Заголовок <span class="text-danger">*</span></label>
                <input id="title" name="title" type="text"
                    class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}" required>
                @error('title')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
            </div>

            <div class="mb-3 text-center">
                <label for="title_desc" class="form-label">Краткое описание заголовка</label>
                <input id="title_desc" name="title_desc" type="text"
                    class="form-control @error('title_desc') is-invalid @enderror" value="{{ old('title_desc') }}">
                @error('title_desc')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
            </div>

            <div class="mb-3 text-center">
                <label for="price" class="form-label">Цена (руб.)</label>
                <input id="price" name="price" type="number" step="0.01" min="0"
                    class="form-control @error('price') is-invalid @enderror" value="{{ old('price') }}">
                @error('price')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
            </div>

            @if ($contentBlock->preview_img && Storage::disk('public')->exists($contentBlock->preview_img))
                <div class="mb-2">
                    <img src="{{ Storage::url($contentBlock->preview_img) }}" class="img-fluid" alt="">
                </div>
                <div class="form-check mb-2">
                    <input class="form-check-input" type="checkbox" name="remove_preview_img" id="remove_preview_img"
                        value="1">
                    <label class="form-check-label" for="remove_preview_img">Удалить превью</label>
                </div>
            @endif

            <input id="preview_img" name="preview_img" type="file" accept="image/*" class="form-control">

            <div class="row align-items-start gap-4">
                {{-- LEFT: Gallery + uploader --}}
                <div class="col-lg-6">
                    <label class="form-label">Фотогалерея</label>

                    <div class="swiper block-gallery-top create-swiper-top" id="createGalleryTop">
                        <div class="swiper-wrapper"><!-- slides generated by JS --></div>
                        <div class="swiper-button-prev create-prev" aria-label="Предыдущий"></div>
                        <div class="swiper-button-next create-next" aria-label="Следующий"></div>
                    </div>

                    <div class="swiper block-gallery-thumbs create-swiper-thumbs mt-3" id="createGalleryThumbs">
                        <div class="swiper-wrapper"><!-- thumbs generated by JS --></div>
                    </div>

                    <div class="mt-3">
                        <label for="images" class="form-label">Загрузить изображения галереи (много)</label>
                        <input type="file" id="images" name="images[]" multiple accept="image/*"
                            class="form-control @error('images.*') is-invalid @enderror">
                        @error('images.*')
                            <div class="invalid-feedback d-block">{{ $message }}</div>
                        @enderror
                        <small class="text-muted">Рекомендуемый формат: WebP, jpg, png. Макс 2MB</small>
                    </div>
                </div>

                {{-- RIGHT: Description --}}
                <div class="col-lg-6">
                    @include('admin.partials.editor', [
                        'id' => 'desc',
                        'name' => 'desc',
                        'value' => old('desc', ''),
                        'label' => 'Описание (справа)',
                    ])
                </div>
            </div>

            {{-- Block 2 --}}
            <div class="row align-items-center mt-4">
                <div class="col-lg-6">
                    <div class="mb-3">
                        <label for="block_2_title" class="form-label">Block 2 — Заголовок</label>
                        <input id="block_2_title" name="block_2_title" type="text"
                            class="form-control @error('block_2_title') is-invalid @enderror"
                            value="{{ old('block_2_title') }}">
                        @error('block_2_title')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>

                    @include('admin.partials.editor', [
                        'id' => 'block_2_desc',
                        'name' => 'block_2_desc',
                        'value' => old('block_2_desc', ''),
                        'label' => 'Block 2 — Текст',
                    ])
                </div>

                <div class="col-lg-6 text-center">
                    <label for="block_2_img" class="form-label">Block 2 — Картинка (право)</label>
                    <input id="block_2_img" name="block_2_img" type="file" accept="image/*"
                        class="form-control mb-3 @error('block_2_img') is-invalid @enderror">
                    @error('block_2_img')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror

                    <div id="block2Preview" class="block2-preview"></div>
                </div>
            </div>

            <div class="mt-4 d-flex gap-2">
                <button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Сохранить</button>
                <a href="{{ route('admin.content-blocks.index') }}" class="btn btn-secondary">Отмена</a>
            </div>
        </form>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            let topSwiper = null;
            let thumbsSwiper = null;

            function initSwipers() {
                if (thumbsSwiper) thumbsSwiper.destroy(true, true);
                if (topSwiper) topSwiper.destroy(true, true);

                thumbsSwiper = new Swiper('#createGalleryThumbs', {
                    spaceBetween: 8,
                    slidesPerView: 4,
                    watchSlidesProgress: true,
                });

                topSwiper = new Swiper('#createGalleryTop', {
                    spaceBetween: 10,
                    navigation: {
                        nextEl: '.create-next',
                        prevEl: '.create-prev'
                    },
                    thumbs: {
                        swiper: thumbsSwiper
                    },
                });
            }

            function filesToSlides(files) {
                const topWrapper = document.querySelector('#createGalleryTop .swiper-wrapper');
                const thumbsWrapper = document.querySelector('#createGalleryThumbs .swiper-wrapper');
                topWrapper.innerHTML = '';
                thumbsWrapper.innerHTML = '';

                Array.from(files).forEach(file => {
                    const url = URL.createObjectURL(file);

                    const slide = document.createElement('div');
                    slide.className = 'swiper-slide';
                    slide.innerHTML = `<img src="${url}" style="width:100%;height:100%;object-fit:cover;">`;
                    topWrapper.appendChild(slide);

                    const thumb = document.createElement('div');
                    thumb.className = 'swiper-slide';
                    thumb.innerHTML = `<img src="${url}" style="width:100%;height:100%;object-fit:cover;">`;
                    thumbsWrapper.appendChild(thumb);
                });

                initSwipers();
            }

            document.getElementById('images').addEventListener('change', function(e) {
                const files = e.target.files;
                filesToSlides(files);
            });

            // preview for block_2_img
            document.getElementById('block_2_img').addEventListener('change', function(e) {
                const preview = document.getElementById('block2Preview');
                preview.innerHTML = '';
                const f = e.target.files[0];
                if (!f) return;
                const url = URL.createObjectURL(f);
                const img = document.createElement('img');
                img.src = url;
                img.style.maxWidth = '100%';
                img.style.borderRadius = '12px';
                preview.appendChild(img);
            });

            // initialize empty swipers
            initSwipers();
        });
    </script>
@endpush
